# Generated by Django 5.1.3 on 2024-11-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_document_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='DocumentQuery',
        ),
    ]
