# Generated by Django 5.1.3 on 2024-11-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_query_documentquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vector_store_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
