# Generated by Django 5.1.3 on 2024-11-25 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_vector_store_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='documentquery',
            name='perplexity_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentquery',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='api.document'),
        ),
    ]
